In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("asmaaabdelwahab/arabic-news-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/arabic-news-dataset

In [ ]:
!mkdir /content/Data
!cp -r /kaggle/input/arabic-news-dataset /content/Data

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/Data/arabic-news-dataset/processed_data.csv')
df

,Title,Content,Link,Category
0,تيرتل تري لابز للتقنيات الحيويه تحصل علي تمويل...,جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...,https://ryadiybusiness.com/%d8%aa%d9%8a%d8%b1%...,ريادة أعمال
1,تعد دراسه الجدوي لمشروعك الناشء 6 عوامل اساسيه,تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...,https://ryadiybusiness.com/%d9%83%d9%8a%d9%81-...,ريادة أعمال
2,منح جاءزه نوبل الطب لاكتشاف مجال التهاب الكبد ...,وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...,https://arabic.sputniknews.com/science/2020100...,علوم وتكنولوجيا
3,هيءه الغذاء والدواء الامريكيه لقاح مودرنا حقق ...,نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...,https://arabic.sputniknews.com/world/202012151...,علوم وتكنولوجيا
4,حظر بروتين الجهاز المناعي يساعد علي محاربه عدو...,دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...,https://arabic.rt.com//technology/1161864-%D8%...,علوم وتكنولوجيا
...,...,...,...,...
8394,قواعد اوروبيه تهدد بخفض 10 ايرادات شركات التكن...,قالت وكاله بلومبرغ الاثنين ان كبري شركات التكن...,https://asharq.com/ar/7vNsbHVkd9fTQhBQI70ASx-ق...,علوم وتكنولوجيا
8395,حوار خاص مهندس سعودي نباتك فكره تهدف لزراعه مل...,بدات الفكره نعومه اظفاره عندما كان السابعه عمر...,https://news.un.org/ar/story/2020/09/1062802,أخرى
8396,كريم تطلق خدمه اطلب اي شيء الجديده,اعلنت منصه كريم 4 فبراير الجاري اطلاق خدمه اطل...,https://ryadiybusiness.com/%d9%83%d8%b1%d9%8a%...,ريادة أعمال
8397,تقرير اممي جديد يشير الي تاثير جاءحه فيروس كور...,وفقا لتقديرات المكتب الاممي المعني بالمخدرات و...,https://news.un.org/ar/story/2020/06/1057232,أخرى
8398,فريق مشترك يتحقق اوضاع النساء والاطفال داخل قو...,تاتي الزياره كجزء تنفيذ اتفاقيه السلام المنشطه...,https://news.un.org/ar/story/2019/11/1043621,أخرى

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Title     8399 non-null   object
 1   Content   8386 non-null   object
 2   Link      8399 non-null   object
 3   Category  8399 non-null   object
dtypes: object(4)
memory usage: 262.6+ KB

In [ ]:
df.describe()

,Title,Content,Link,Category
count,8399,8386,8399,8399
unique,7951,7923,7976,3
top,صندوق Impact Seed اول صندوق سعودي ينضم لشبكه D...,امل دخان نسبه صناديق الاستثمار الشركات الناشءه...,https://ryadiybusiness.com/%d8%a2%d9%85%d9%84-...,علوم وتكنولوجيا
freq,4,4,4,2800

In [ ]:
df.isnull().sum()

Title        0
Content     13
Link         0
Category     0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.isnull().sum()

Title       0
Content     0
Link        0
Category    0
dtype: int64

In [ ]:
import re

def normalize_arabic(text):
    text = re.sub(r'[\u064B-\u065F\u0670]', '', text)
    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ؤ", "ء", text)
    text = re.sub("ئ", "ء", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("گ", "ك", text)
    text = re.sub("ڤ", "ف", text)
    text = re.sub("چ", "ج", text)
    text = re.sub("پ", "ب", text)
    text = re.sub("ڜ", "ش", text)
    text = re.sub("ڪ", "ك", text)
    text = re.sub("ڧ", "ق", text)
    text = re.sub("ٱ", "ا", text)
    return text

In [ ]:
df['cleaned_text']=df['Content'].apply(normalize_arabic)

/tmp/ipython-input-1035548803.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_text']=df['Content'].apply(normalize_arabic)

In [ ]:
df['cleaned_text']

0       جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...
1       تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...
2       وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...
3       نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...
4       دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...
                              ...
8394    قالت وكاله بلومبرغ الاثنين ان كبري شركات التكن...
8395    بدات الفكره نعومه اظفاره عندما كان السابعه عمر...
8396    اعلنت منصه كريم 4 فبراير الجاري اطلاق خدمه اطل...
8397    وفقا لتقديرات المكتب الاممي المعني بالمخدرات و...
8398    تاتي الزياره كجزء تنفيذ اتفاقيه السلام المنشطه...
Name: cleaned_text, Length: 8386, dtype: object

In [ ]:
all_text = ' '.join(df['cleaned_text'])
unique_chars = sorted(set(all_text))
print("Unique characters:", unique_chars)
len(unique_chars)

Unique characters: [' ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '©', '«', '\xad', '®', '°', '±', '²', 'µ', '·', '»', '¾', 'Ä', 'à', 'á', 'â', 'ä', 'ç', 'é', 'í', 'ï', 'ñ', 'ó', 'ö', 'ø', 'ü', 'ā', 'č', 'ī', 'ł', 'Α', 'Ε', 'Π', 'Υ', 'ά', 'έ', 'ή', 'ί', 'α', 'β', 'γ', 'δ', 'ε', 'ζ', 'η', 'θ', 'ι', 'κ', 'λ', 'μ', 'ν', 'ο', 'π', 'ρ', 'ς', 'σ', 'τ', 'υ', 'φ', 'ω', 'ό', 'ύ', 'А', 'Б', 'В', 'Г', 'Д', 'Е', 'И', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'Ф', 'Х', 'Ч', 'Э', 'Ю', 'Я', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ё', 'א', 'ד', 'ו', 'ח', 'י', 'ך', 'ל', 'נ', '\u061c', 'ء', 'ا', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', '٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩', '٪', 'ٲ', 'ک', 'ھ', 'ی', 'ۚ', '۰', '۱', '۲', '۷', '۹', 'ക', 'ച', 'ണ', 'മ', 'ര', 'ഷ', 'ഹ', 'ാ', 'ി', 'ൃ', '്', 'ൻ', '\u200b', '\u200c', '\u200d', '\u200e', '\u200f', '—', '‘', '’', '•', '\u202a', '\u202b', '\u202c', '\u202d', '′', '″', '‼', '⁉', '\u2060', '\u2066', '\u2067', '\u2069', '⃣', '™', '→', '⏪', '⏰', '⏸', '►', '●', '☀', '☄', '☑', '☠', '♀', '♂', '♥', '♦', '⚕', '⚠', '⚡', '⚽', '⛏', '⛹', '✅', '✔', '✨', '❓', '❗', '❤', '➖', '➡', '⬅', '⬆', '⬇', '⭐', '川', '果', '水', '浅', '蓮', '️', 'ﺋ', 'ﺌ', 'ﺍ', 'ﺎ', 'ﺐ', 'ﺑ', 'ﺒ', 'ﺔ', 'ﺕ', 'ﺗ', 'ﺘ', 'ﺛ', 'ﺞ', 'ﺠ', 'ﺣ', 'ﺨ', 'ﺪ', 'ﺮ', 'ﺴ', 'ﻃ', 'ﻇ', 'ﻊ', 'ﻌ', 'ﻐ', 'ﻒ', 'ﻓ', 'ﻗ', 'ﻘ', 'ﻛ', 'ﻟ', 'ﻠ', 'ﻣ', 'ﻤ', 'ﻪ', 'ﻮ', 'ﻴ', 'ﻷ', 'ﻹ', 'ﻻ', 'ﻼ', '🇦', '🇧', '🇨', '🇩', '🇪', '🇫', '🇬', '🇭', '🇮', '🇰', '🇱', '🇲', '🇳', '🇴', '🇵', '🇶', '🇷', '🇸', '🇺', '🇼', '🌊', '🌍', '🌎', '🌔', '🌙', '🌚', '🌟', '🌠', '🌱', '🌼', '🌽', '🌾', '🍏', '🍺', '🍼', '🎒', '🎓', '🎥', '🎦', '🎨', '🎩', '🎶', '🎼', '🏃', '🏗', '🏠', '🏥', '🏴', '🏻', '🏼', '🏽', '🏾', '🐄', '🐊', '🐍', '🐒', '🐓', '🐖', '🐝', '🐪', '👇', '👈', '👉', '👏', '👐', '👤', '👥', '👦', '👧', '👨', '👩', '👶', '👷', '👻', '💀', '💉', '💊', '💒', '💙', '💟', '💦', '💪', '💬', '💭', '💳', '📄', '📌', '📖', '📙', '📚', '📞', '📢', '📧', '📰', '📱', '📲', '📷', '📸', '📹', '📺', '📽', '🔍', '🔖', '🔗', '🔝', '🔟', '🔥', '🔬', '🔴', '🔵', '🔶', '🔷', '🔸', '🔹', '🕐', '🕖', '🗓', '🗞', '🗣', '🗺', '😁', '😃', '😊', '😍', '😎', '😭', '😱', '😷', '🙂', '🙌', '🚀', '🚨', '🚭', '🚿', '🛒', '🛣', '🟡', '🟢', '🤒', '🤓', '🤔', '🤤', '🤦', '🤧', '🤭', '🤯', '🤰', '🤱', '🥐', '🥚', '🥰', '🥳', '🦇', '🦎', '🦕', '🦖', '🦗', '🦱', '🦸', '🧍', '🧐', '🧑', '🧒', '🧕', '🧘', '🧠', '🧤', '🧪', '🧬', '🧵', '🧼', '🩸', '🩺', '🪐', '🫁']

526

In [ ]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.14.1-py3-none-any.whl (590 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 10.2 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.14.1

In [ ]:
import emoji

def handle_emojis(text, mode='remove'):
    if mode == 'remove':
        return emoji.replace_emoji(text, '')
    elif mode == 'description':
        return emoji.demojize(text, language='ar')
    return text

In [ ]:
df['text_no_emoji'] = df['cleaned_text'].apply(handle_emojis, mode='remove')
display(df[['cleaned_text', 'text_no_emoji']].head())

/tmp/ipython-input-1284920908.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text_no_emoji'] = df['cleaned_text'].apply(handle_emojis, mode='remove')

,cleaned_text,text_no_emoji
0,جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...,جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...
1,تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...,تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...
2,وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...,وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...
3,نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...,نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...
4,دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...,دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...

In [ ]:
all_text = ' '.join(df['cleaned_text'])
unique_chars = sorted(set(all_text))
print("Unique characters:", unique_chars)
len(unique_chars)

Unique characters: [' ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '©', '«', '\xad', '®', '°', '±', '²', 'µ', '·', '»', '¾', 'Ä', 'à', 'á', 'â', 'ä', 'ç', 'é', 'í', 'ï', 'ñ', 'ó', 'ö', 'ø', 'ü', 'ā', 'č', 'ī', 'ł', 'Α', 'Ε', 'Π', 'Υ', 'ά', 'έ', 'ή', 'ί', 'α', 'β', 'γ', 'δ', 'ε', 'ζ', 'η', 'θ', 'ι', 'κ', 'λ', 'μ', 'ν', 'ο', 'π', 'ρ', 'ς', 'σ', 'τ', 'υ', 'φ', 'ω', 'ό', 'ύ', 'А', 'Б', 'В', 'Г', 'Д', 'Е', 'И', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'Ф', 'Х', 'Ч', 'Э', 'Ю', 'Я', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ё', 'א', 'ד', 'ו', 'ח', 'י', 'ך', 'ל', 'נ', '\u061c', 'ء', 'ا', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', '٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩', '٪', 'ٲ', 'ک', 'ھ', 'ی', 'ۚ', '۰', '۱', '۲', '۷', '۹', 'ക', 'ച', 'ണ', 'മ', 'ര', 'ഷ', 'ഹ', 'ാ', 'ി', 'ൃ', '്', 'ൻ', '\u200b', '\u200c', '\u200d', '\u200e', '\u200f', '—', '‘', '’', '•', '\u202a', '\u202b', '\u202c', '\u202d', '′', '″', '‼', '⁉', '\u2060', '\u2066', '\u2067', '\u2069', '⃣', '™', '→', '⏪', '⏰', '⏸', '►', '●', '☀', '☄', '☑', '☠', '♀', '♂', '♥', '♦', '⚕', '⚠', '⚡', '⚽', '⛏', '⛹', '✅', '✔', '✨', '❓', '❗', '❤', '➖', '➡', '⬅', '⬆', '⬇', '⭐', '川', '果', '水', '浅', '蓮', '️', 'ﺋ', 'ﺌ', 'ﺍ', 'ﺎ', 'ﺐ', 'ﺑ', 'ﺒ', 'ﺔ', 'ﺕ', 'ﺗ', 'ﺘ', 'ﺛ', 'ﺞ', 'ﺠ', 'ﺣ', 'ﺨ', 'ﺪ', 'ﺮ', 'ﺴ', 'ﻃ', 'ﻇ', 'ﻊ', 'ﻌ', 'ﻐ', 'ﻒ', 'ﻓ', 'ﻗ', 'ﻘ', 'ﻛ', 'ﻟ', 'ﻠ', 'ﻣ', 'ﻤ', 'ﻪ', 'ﻮ', 'ﻴ', 'ﻷ', 'ﻹ', 'ﻻ', 'ﻼ', '🇦', '🇧', '🇨', '🇩', '🇪', '🇫', '🇬', '🇭', '🇮', '🇰', '🇱', '🇲', '🇳', '🇴', '🇵', '🇶', '🇷', '🇸', '🇺', '🇼', '🌊', '🌍', '🌎', '🌔', '🌙', '🌚', '🌟', '🌠', '🌱', '🌼', '🌽', '🌾', '🍏', '🍺', '🍼', '🎒', '🎓', '🎥', '🎦', '🎨', '🎩', '🎶', '🎼', '🏃', '🏗', '🏠', '🏥', '🏴', '🏻', '🏼', '🏽', '🏾', '🐄', '🐊', '🐍', '🐒', '🐓', '🐖', '🐝', '🐪', '👇', '👈', '👉', '👏', '👐', '👤', '👥', '👦', '👧', '👨', '👩', '👶', '👷', '👻', '💀', '💉', '💊', '💒', '💙', '💟', '💦', '💪', '💬', '💭', '💳', '📄', '📌', '📖', '📙', '📚', '📞', '📢', '📧', '📰', '📱', '📲', '📷', '📸', '📹', '📺', '📽', '🔍', '🔖', '🔗', '🔝', '🔟', '🔥', '🔬', '🔴', '🔵', '🔶', '🔷', '🔸', '🔹', '🕐', '🕖', '🗓', '🗞', '🗣', '🗺', '😁', '😃', '😊', '😍', '😎', '😭', '😱', '😷', '🙂', '🙌', '🚀', '🚨', '🚭', '🚿', '🛒', '🛣', '🟡', '🟢', '🤒', '🤓', '🤔', '🤤', '🤦', '🤧', '🤭', '🤯', '🤰', '🤱', '🥐', '🥚', '🥰', '🥳', '🦇', '🦎', '🦕', '🦖', '🦗', '🦱', '🦸', '🧍', '🧐', '🧑', '🧒', '🧕', '🧘', '🧠', '🧤', '🧪', '🧬', '🧵', '🧼', '🩸', '🩺', '🪐', '🫁']

526

In [ ]:
all_text = ' '.join(df['cleaned_text'])
unique_chars = sorted(set(all_text))
print("Unique characters:", unique_chars)
len(unique_chars)

Unique characters: [' ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '©', '«', '\xad', '®', '°', '±', '²', 'µ', '·', '»', '¾', 'Ä', 'à', 'á', 'â', 'ä', 'ç', 'é', 'í', 'ï', 'ñ', 'ó', 'ö', 'ø', 'ü', 'ā', 'č', 'ī', 'ł', 'Α', 'Ε', 'Π', 'Υ', 'ά', 'έ', 'ή', 'ί', 'α', 'β', 'γ', 'δ', 'ε', 'ζ', 'η', 'θ', 'ι', 'κ', 'λ', 'μ', 'ν', 'ο', 'π', 'ρ', 'ς', 'σ', 'τ', 'υ', 'φ', 'ω', 'ό', 'ύ', 'А', 'Б', 'В', 'Г', 'Д', 'Е', 'И', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'Ф', 'Х', 'Ч', 'Э', 'Ю', 'Я', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ё', 'א', 'ד', 'ו', 'ח', 'י', 'ך', 'ל', 'נ', '\u061c', 'ء', 'ا', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', '٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩', '٪', 'ٲ', 'ک', 'ھ', 'ی', 'ۚ', '۰', '۱', '۲', '۷', '۹', 'ക', 'ച', 'ണ', 'മ', 'ര', 'ഷ', 'ഹ', 'ാ', 'ി', 'ൃ', '്', 'ൻ', '\u200b', '\u200c', '\u200d', '\u200e', '\u200f', '—', '‘', '’', '•', '\u202a', '\u202b', '\u202c', '\u202d', '′', '″', '‼', '⁉', '\u2060', '\u2066', '\u2067', '\u2069', '⃣', '™', '→', '⏪', '⏰', '⏸', '►', '●', '☀', '☄', '☑', '☠', '♀', '♂', '♥', '♦', '⚕', '⚠', '⚡', '⚽', '⛏', '⛹', '✅', '✔', '✨', '❓', '❗', '❤', '➖', '➡', '⬅', '⬆', '⬇', '⭐', '川', '果', '水', '浅', '蓮', '️', 'ﺋ', 'ﺌ', 'ﺍ', 'ﺎ', 'ﺐ', 'ﺑ', 'ﺒ', 'ﺔ', 'ﺕ', 'ﺗ', 'ﺘ', 'ﺛ', 'ﺞ', 'ﺠ', 'ﺣ', 'ﺨ', 'ﺪ', 'ﺮ', 'ﺴ', 'ﻃ', 'ﻇ', 'ﻊ', 'ﻌ', 'ﻐ', 'ﻒ', 'ﻓ', 'ﻗ', 'ﻘ', 'ﻛ', 'ﻟ', 'ﻠ', 'ﻣ', 'ﻤ', 'ﻪ', 'ﻮ', 'ﻴ', 'ﻷ', 'ﻹ', 'ﻻ', 'ﻼ', '🇦', '🇧', '🇨', '🇩', '🇪', '🇫', '🇬', '🇭', '🇮', '🇰', '🇱', '🇲', '🇳', '🇴', '🇵', '🇶', '🇷', '🇸', '🇺', '🇼', '🌊', '🌍', '🌎', '🌔', '🌙', '🌚', '🌟', '🌠', '🌱', '🌼', '🌽', '🌾', '🍏', '🍺', '🍼', '🎒', '🎓', '🎥', '🎦', '🎨', '🎩', '🎶', '🎼', '🏃', '🏗', '🏠', '🏥', '🏴', '🏻', '🏼', '🏽', '🏾', '🐄', '🐊', '🐍', '🐒', '🐓', '🐖', '🐝', '🐪', '👇', '👈', '👉', '👏', '👐', '👤', '👥', '👦', '👧', '👨', '👩', '👶', '👷', '👻', '💀', '💉', '💊', '💒', '💙', '💟', '💦', '💪', '💬', '💭', '💳', '📄', '📌', '📖', '📙', '📚', '📞', '📢', '📧', '📰', '📱', '📲', '📷', '📸', '📹', '📺', '📽', '🔍', '🔖', '🔗', '🔝', '🔟', '🔥', '🔬', '🔴', '🔵', '🔶', '🔷', '🔸', '🔹', '🕐', '🕖', '🗓', '🗞', '🗣', '🗺', '😁', '😃', '😊', '😍', '😎', '😭', '😱', '😷', '🙂', '🙌', '🚀', '🚨', '🚭', '🚿', '🛒', '🛣', '🟡', '🟢', '🤒', '🤓', '🤔', '🤤', '🤦', '🤧', '🤭', '🤯', '🤰', '🤱', '🥐', '🥚', '🥰', '🥳', '🦇', '🦎', '🦕', '🦖', '🦗', '🦱', '🦸', '🧍', '🧐', '🧑', '🧒', '🧕', '🧘', '🧠', '🧤', '🧪', '🧬', '🧵', '🧼', '🩸', '🩺', '🪐', '🫁']

526

In [ ]:
def handle_numbers_and_special_chars(text, mode='remove'):
    if mode == 'remove':
        text = re.sub(r'\d+', '', text)
        return text
    elif mode == 'normalize':
        number_map = {
                      '٠': 'صفر',
                      '١': 'واحد',
                      '٢': 'اثنان',
                      '٣': 'ثلاثة',
                      '٤': 'أربعة',
                      '٥': 'خمسة',
                      '٦': 'ستة',
                      '٧': 'سبعة',
                      '٨': 'ثمانية',
                      '٩': 'تسعة',
                      '0': 'صفر',
                      '1': 'واحد',
                      '2': 'اثنان',
                      '3': 'ثلاثة',
                      '4': 'أربعة',
                      '5': 'خمسة',
                      '6': 'ستة',
                      '7': 'سبعة',
                      '8': 'ثمانية',
                      '9': 'تسعة'
                  }
        for arabic, name in number_map.items():
            text = text.replace(arabic, name)
        return text

In [ ]:
all_text = ' '.join(df['cleaned_text'])
unique_chars = sorted(set(all_text))
print("Unique characters:", unique_chars)
len(unique_chars)

Unique characters: [' ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '©', '«', '\xad', '®', '°', '±', '²', 'µ', '·', '»', '¾', 'Ä', 'à', 'á', 'â', 'ä', 'ç', 'é', 'í', 'ï', 'ñ', 'ó', 'ö', 'ø', 'ü', 'ā', 'č', 'ī', 'ł', 'Α', 'Ε', 'Π', 'Υ', 'ά', 'έ', 'ή', 'ί', 'α', 'β', 'γ', 'δ', 'ε', 'ζ', 'η', 'θ', 'ι', 'κ', 'λ', 'μ', 'ν', 'ο', 'π', 'ρ', 'ς', 'σ', 'τ', 'υ', 'φ', 'ω', 'ό', 'ύ', 'А', 'Б', 'В', 'Г', 'Д', 'Е', 'И', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'Ф', 'Х', 'Ч', 'Э', 'Ю', 'Я', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ё', 'א', 'ד', 'ו', 'ח', 'י', 'ך', 'ל', 'נ', '\u061c', 'ء', 'ا', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', '٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩', '٪', 'ٲ', 'ک', 'ھ', 'ی', 'ۚ', '۰', '۱', '۲', '۷', '۹', 'ക', 'ച', 'ണ', 'മ', 'ര', 'ഷ', 'ഹ', 'ാ', 'ി', 'ൃ', '്', 'ൻ', '\u200b', '\u200c', '\u200d', '\u200e', '\u200f', '—', '‘', '’', '•', '\u202a', '\u202b', '\u202c', '\u202d', '′', '″', '‼', '⁉', '\u2060', '\u2066', '\u2067', '\u2069', '⃣', '™', '→', '⏪', '⏰', '⏸', '►', '●', '☀', '☄', '☑', '☠', '♀', '♂', '♥', '♦', '⚕', '⚠', '⚡', '⚽', '⛏', '⛹', '✅', '✔', '✨', '❓', '❗', '❤', '➖', '➡', '⬅', '⬆', '⬇', '⭐', '川', '果', '水', '浅', '蓮', '️', 'ﺋ', 'ﺌ', 'ﺍ', 'ﺎ', 'ﺐ', 'ﺑ', 'ﺒ', 'ﺔ', 'ﺕ', 'ﺗ', 'ﺘ', 'ﺛ', 'ﺞ', 'ﺠ', 'ﺣ', 'ﺨ', 'ﺪ', 'ﺮ', 'ﺴ', 'ﻃ', 'ﻇ', 'ﻊ', 'ﻌ', 'ﻐ', 'ﻒ', 'ﻓ', 'ﻗ', 'ﻘ', 'ﻛ', 'ﻟ', 'ﻠ', 'ﻣ', 'ﻤ', 'ﻪ', 'ﻮ', 'ﻴ', 'ﻷ', 'ﻹ', 'ﻻ', 'ﻼ', '🇦', '🇧', '🇨', '🇩', '🇪', '🇫', '🇬', '🇭', '🇮', '🇰', '🇱', '🇲', '🇳', '🇴', '🇵', '🇶', '🇷', '🇸', '🇺', '🇼', '🌊', '🌍', '🌎', '🌔', '🌙', '🌚', '🌟', '🌠', '🌱', '🌼', '🌽', '🌾', '🍏', '🍺', '🍼', '🎒', '🎓', '🎥', '🎦', '🎨', '🎩', '🎶', '🎼', '🏃', '🏗', '🏠', '🏥', '🏴', '🏻', '🏼', '🏽', '🏾', '🐄', '🐊', '🐍', '🐒', '🐓', '🐖', '🐝', '🐪', '👇', '👈', '👉', '👏', '👐', '👤', '👥', '👦', '👧', '👨', '👩', '👶', '👷', '👻', '💀', '💉', '💊', '💒', '💙', '💟', '💦', '💪', '💬', '💭', '💳', '📄', '📌', '📖', '📙', '📚', '📞', '📢', '📧', '📰', '📱', '📲', '📷', '📸', '📹', '📺', '📽', '🔍', '🔖', '🔗', '🔝', '🔟', '🔥', '🔬', '🔴', '🔵', '🔶', '🔷', '🔸', '🔹', '🕐', '🕖', '🗓', '🗞', '🗣', '🗺', '😁', '😃', '😊', '😍', '😎', '😭', '😱', '😷', '🙂', '🙌', '🚀', '🚨', '🚭', '🚿', '🛒', '🛣', '🟡', '🟢', '🤒', '🤓', '🤔', '🤤', '🤦', '🤧', '🤭', '🤯', '🤰', '🤱', '🥐', '🥚', '🥰', '🥳', '🦇', '🦎', '🦕', '🦖', '🦗', '🦱', '🦸', '🧍', '🧐', '🧑', '🧒', '🧕', '🧘', '🧠', '🧤', '🧪', '🧬', '🧵', '🧼', '🩸', '🩺', '🪐', '🫁']

526

In [ ]:
df['cleaned_text']=df['cleaned_text'].apply(handle_numbers_and_special_chars)

/tmp/ipython-input-1226662523.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_text']=df['cleaned_text'].apply(handle_numbers_and_special_chars)

In [ ]:
all_text = ' '.join(df['cleaned_text'])
unique_chars = sorted(set(all_text))
print("Unique characters:", unique_chars)
len(unique_chars)

Unique characters: [' ', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '©', '«', '\xad', '®', '°', '±', '²', 'µ', '·', '»', '¾', 'Ä', 'à', 'á', 'â', 'ä', 'ç', 'é', 'í', 'ï', 'ñ', 'ó', 'ö', 'ø', 'ü', 'ā', 'č', 'ī', 'ł', 'Α', 'Ε', 'Π', 'Υ', 'ά', 'έ', 'ή', 'ί', 'α', 'β', 'γ', 'δ', 'ε', 'ζ', 'η', 'θ', 'ι', 'κ', 'λ', 'μ', 'ν', 'ο', 'π', 'ρ', 'ς', 'σ', 'τ', 'υ', 'φ', 'ω', 'ό', 'ύ', 'А', 'Б', 'В', 'Г', 'Д', 'Е', 'И', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'Ф', 'Х', 'Ч', 'Э', 'Ю', 'Я', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ё', 'א', 'ד', 'ו', 'ח', 'י', 'ך', 'ל', 'נ', '\u061c', 'ء', 'ا', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', '٪', 'ٲ', 'ک', 'ھ', 'ی', 'ۚ', 'ക', 'ച', 'ണ', 'മ', 'ര', 'ഷ', 'ഹ', 'ാ', 'ി', 'ൃ', '്', 'ൻ', '\u200b', '\u200c', '\u200d', '\u200e', '\u200f', '—', '‘', '’', '•', '\u202a', '\u202b', '\u202c', '\u202d', '′', '″', '‼', '⁉', '\u2060', '\u2066', '\u2067', '\u2069', '⃣', '™', '→', '⏪', '⏰', '⏸', '►', '●', '☀', '☄', '☑', '☠', '♀', '♂', '♥', '♦', '⚕', '⚠', '⚡', '⚽', '⛏', '⛹', '✅', '✔', '✨', '❓', '❗', '❤', '➖', '➡', '⬅', '⬆', '⬇', '⭐', '川', '果', '水', '浅', '蓮', '️', 'ﺋ', 'ﺌ', 'ﺍ', 'ﺎ', 'ﺐ', 'ﺑ', 'ﺒ', 'ﺔ', 'ﺕ', 'ﺗ', 'ﺘ', 'ﺛ', 'ﺞ', 'ﺠ', 'ﺣ', 'ﺨ', 'ﺪ', 'ﺮ', 'ﺴ', 'ﻃ', 'ﻇ', 'ﻊ', 'ﻌ', 'ﻐ', 'ﻒ', 'ﻓ', 'ﻗ', 'ﻘ', 'ﻛ', 'ﻟ', 'ﻠ', 'ﻣ', 'ﻤ', 'ﻪ', 'ﻮ', 'ﻴ', 'ﻷ', 'ﻹ', 'ﻻ', 'ﻼ', '🇦', '🇧', '🇨', '🇩', '🇪', '🇫', '🇬', '🇭', '🇮', '🇰', '🇱', '🇲', '🇳', '🇴', '🇵', '🇶', '🇷', '🇸', '🇺', '🇼', '🌊', '🌍', '🌎', '🌔', '🌙', '🌚', '🌟', '🌠', '🌱', '🌼', '🌽', '🌾', '🍏', '🍺', '🍼', '🎒', '🎓', '🎥', '🎦', '🎨', '🎩', '🎶', '🎼', '🏃', '🏗', '🏠', '🏥', '🏴', '🏻', '🏼', '🏽', '🏾', '🐄', '🐊', '🐍', '🐒', '🐓', '🐖', '🐝', '🐪', '👇', '👈', '👉', '👏', '👐', '👤', '👥', '👦', '👧', '👨', '👩', '👶', '👷', '👻', '💀', '💉', '💊', '💒', '💙', '💟', '💦', '💪', '💬', '💭', '💳', '📄', '📌', '📖', '📙', '📚', '📞', '📢', '📧', '📰', '📱', '📲', '📷', '📸', '📹', '📺', '📽', '🔍', '🔖', '🔗', '🔝', '🔟', '🔥', '🔬', '🔴', '🔵', '🔶', '🔷', '🔸', '🔹', '🕐', '🕖', '🗓', '🗞', '🗣', '🗺', '😁', '😃', '😊', '😍', '😎', '😭', '😱', '😷', '🙂', '🙌', '🚀', '🚨', '🚭', '🚿', '🛒', '🛣', '🟡', '🟢', '🤒', '🤓', '🤔', '🤤', '🤦', '🤧', '🤭', '🤯', '🤰', '🤱', '🥐', '🥚', '🥰', '🥳', '🦇', '🦎', '🦕', '🦖', '🦗', '🦱', '🦸', '🧍', '🧐', '🧑', '🧒', '🧕', '🧘', '🧠', '🧤', '🧪', '🧬', '🧵', '🧼', '🩸', '🩺', '🪐', '🫁']

501

In [ ]:
arabic_punctuations = '''`÷×؛<>_()*&^%][ـ،/:"؟.,'{}~¦+|!”…“–ـ'''
english_punctuations = r"""!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"""

all_punctuations = arabic_punctuations + english_punctuations

def remove_arabic_punctuations(text):
    return re.sub(f"[{re.escape(all_punctuations)}]", " ", text)

In [ ]:
df['cleaned_text']=df['cleaned_text'].apply(remove_arabic_punctuations)

/tmp/ipython-input-824365669.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_text']=df['cleaned_text'].apply(remove_arabic_punctuations)

In [ ]:
def remove_diacritics(text):
    arabic_diacritics = re.compile("""
         ّ    |  # Shadda
         َ    |  # Fatha
         ً    |  # Tanwin Fath
         ُ    |  # Damma
         ٌ    |  # Tanwin Damm
         ِ    |  # Kasra
         ٍ    |  # Tanwin Kasr
         ْ    |  # Sukun
         ـ       # Tatwil (Kashida)
    """, re.VERBOSE)

    return re.sub(arabic_diacritics, '', text)

In [ ]:
df['cleaned_text']=df['cleaned_text'].apply(remove_diacritics)

/tmp/ipython-input-810679453.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_text']=df['cleaned_text'].apply(remove_diacritics)

In [ ]:
df['cleaned_text']

0       جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...
1       تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...
2       وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...
3       نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...
4       دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...
                              ...
8394    قالت وكاله بلومبرغ الاثنين ان كبري شركات التكن...
8395    بدات الفكره نعومه اظفاره عندما كان السابعه عمر...
8396    اعلنت منصه كريم  فبراير الجاري اطلاق خدمه اطلب...
8397    وفقا لتقديرات المكتب الاممي المعني بالمخدرات و...
8398    تاتي الزياره كجزء تنفيذ اتفاقيه السلام المنشطه...
Name: cleaned_text, Length: 8386, dtype: object

In [ ]:
all_text = ' '.join(df['cleaned_text'])
unique_chars = sorted(set(all_text))
print("Unique characters:", unique_chars)
len(unique_chars)

Unique characters: [' ', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '©', '«', '\xad', '®', '°', '±', '²', 'µ', '·', '»', '¾', 'Ä', 'à', 'á', 'â', 'ä', 'ç', 'é', 'í', 'ï', 'ñ', 'ó', 'ö', 'ø', 'ü', 'ā', 'č', 'ī', 'ł', 'Α', 'Ε', 'Π', 'Υ', 'ά', 'έ', 'ή', 'ί', 'α', 'β', 'γ', 'δ', 'ε', 'ζ', 'η', 'θ', 'ι', 'κ', 'λ', 'μ', 'ν', 'ο', 'π', 'ρ', 'ς', 'σ', 'τ', 'υ', 'φ', 'ω', 'ό', 'ύ', 'А', 'Б', 'В', 'Г', 'Д', 'Е', 'И', 'К', 'Л', 'М', 'Н', 'О', 'П', 'Р', 'С', 'Т', 'Ф', 'Х', 'Ч', 'Э', 'Ю', 'Я', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ё', 'א', 'ד', 'ו', 'ח', 'י', 'ך', 'ל', 'נ', '\u061c', 'ء', 'ا', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', '٪', 'ٲ', 'ک', 'ھ', 'ی', 'ۚ', 'ക', 'ച', 'ണ', 'മ', 'ര', 'ഷ', 'ഹ', 'ാ', 'ി', 'ൃ', '്', 'ൻ', '\u200b', '\u200c', '\u200d', '\u200e', '\u200f', '—', '‘', '’', '•', '\u202a', '\u202b', '\u202c', '\u202d', '′', '″', '‼', '⁉', '\u2060', '\u2066', '\u2067', '\u2069', '⃣', '™', '→', '⏪', '⏰', '⏸', '►', '●', '☀', '☄', '☑', '☠', '♀', '♂', '♥', '♦', '⚕', '⚠', '⚡', '⚽', '⛏', '⛹', '✅', '✔', '✨', '❓', '❗', '❤', '➖', '➡', '⬅', '⬆', '⬇', '⭐', '川', '果', '水', '浅', '蓮', '️', 'ﺋ', 'ﺌ', 'ﺍ', 'ﺎ', 'ﺐ', 'ﺑ', 'ﺒ', 'ﺔ', 'ﺕ', 'ﺗ', 'ﺘ', 'ﺛ', 'ﺞ', 'ﺠ', 'ﺣ', 'ﺨ', 'ﺪ', 'ﺮ', 'ﺴ', 'ﻃ', 'ﻇ', 'ﻊ', 'ﻌ', 'ﻐ', 'ﻒ', 'ﻓ', 'ﻗ', 'ﻘ', 'ﻛ', 'ﻟ', 'ﻠ', 'ﻣ', 'ﻤ', 'ﻪ', 'ﻮ', 'ﻴ', 'ﻷ', 'ﻹ', 'ﻻ', 'ﻼ', '🇦', '🇧', '🇨', '🇩', '🇪', '🇫', '🇬', '🇭', '🇮', '🇰', '🇱', '🇲', '🇳', '🇴', '🇵', '🇶', '🇷', '🇸', '🇺', '🇼', '🌊', '🌍', '🌎', '🌔', '🌙', '🌚', '🌟', '🌠', '🌱', '🌼', '🌽', '🌾', '🍏', '🍺', '🍼', '🎒', '🎓', '🎥', '🎦', '🎨', '🎩', '🎶', '🎼', '🏃', '🏗', '🏠', '🏥', '🏴', '🏻', '🏼', '🏽', '🏾', '🐄', '🐊', '🐍', '🐒', '🐓', '🐖', '🐝', '🐪', '👇', '👈', '👉', '👏', '👐', '👤', '👥', '👦', '👧', '👨', '👩', '👶', '👷', '👻', '💀', '💉', '💊', '💒', '💙', '💟', '💦', '💪', '💬', '💭', '💳', '📄', '📌', '📖', '📙', '📚', '📞', '📢', '📧', '📰', '📱', '📲', '📷', '📸', '📹', '📺', '📽', '🔍', '🔖', '🔗', '🔝', '🔟', '🔥', '🔬', '🔴', '🔵', '🔶', '🔷', '🔸', '🔹', '🕐', '🕖', '🗓', '🗞', '🗣', '🗺', '😁', '😃', '😊', '😍', '😎', '😭', '😱', '😷', '🙂', '🙌', '🚀', '🚨', '🚭', '🚿', '🛒', '🛣', '🟡', '🟢', '🤒', '🤓', '🤔', '🤤', '🤦', '🤧', '🤭', '🤯', '🤰', '🤱', '🥐', '🥚', '🥰', '🥳', '🦇', '🦎', '🦕', '🦖', '🦗', '🦱', '🦸', '🧍', '🧐', '🧑', '🧒', '🧕', '🧘', '🧠', '🧤', '🧪', '🧬', '🧵', '🧼', '🩸', '🩺', '🪐', '🫁']

501

In [ ]:
def remove_non_arabic(text):
    arabic_chars = re.compile(r'[^\u0600-\u06FF\s]+')
    return arabic_chars.sub('', text)

df['cleaned_text'] = df['cleaned_text'].apply(remove_non_arabic)
display(df.head())

/tmp/ipython-input-801629276.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_text'] = df['cleaned_text'].apply(remove_non_arabic)

,Title,Content,Link,Category,cleaned_text,text_no_emoji
0,تيرتل تري لابز للتقنيات الحيويه تحصل علي تمويل...,جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...,https://ryadiybusiness.com/%d8%aa%d9%8a%d8%b1%...,ريادة أعمال,جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...,جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...
1,تعد دراسه الجدوي لمشروعك الناشء 6 عوامل اساسيه,تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...,https://ryadiybusiness.com/%d9%83%d9%8a%d9%81-...,ريادة أعمال,تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...,تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...
2,منح جاءزه نوبل الطب لاكتشاف مجال التهاب الكبد ...,وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...,https://arabic.sputniknews.com/science/2020100...,علوم وتكنولوجيا,وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...,وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...
3,هيءه الغذاء والدواء الامريكيه لقاح مودرنا حقق ...,نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...,https://arabic.sputniknews.com/world/202012151...,علوم وتكنولوجيا,نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...,نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...
4,حظر بروتين الجهاز المناعي يساعد علي محاربه عدو...,دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...,https://arabic.rt.com//technology/1161864-%D8%...,علوم وتكنولوجيا,دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...,دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...

In [ ]:
all_text = ' '.join(df['cleaned_text'])
unique_chars = sorted(set(all_text))
print("Unique characters:", unique_chars)
len(unique_chars)

Unique characters: [' ', '\u061c', 'ء', 'ا', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي', '٪', 'ٲ', 'ک', 'ھ', 'ی', 'ۚ']

37

In [ ]:
df['cleaned_text']

0       جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...
1       تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...
2       وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...
3       نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...
4       دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...
                              ...
8394    قالت وكاله بلومبرغ الاثنين ان كبري شركات التكن...
8395    بدات الفكره نعومه اظفاره عندما كان السابعه عمر...
8396    اعلنت منصه كريم  فبراير الجاري اطلاق خدمه اطلب...
8397    وفقا لتقديرات المكتب الاممي المعني بالمخدرات و...
8398    تاتي الزياره كجزء تنفيذ اتفاقيه السلام المنشطه...
Name: cleaned_text, Length: 8386, dtype: object

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.isri import ISRIStemmer
nltk.download('punkt_tab')
nltk.download('punkt')
nltk.download('stopwords')

def preprocess_arabic_text(text):

    tokens = word_tokenize(text)

    arabic_stopwords = set(stopwords.words('arabic'))

    stemmer = ISRIStemmer()

    processed = [stemmer.stem(word) for word in tokens if word not in arabic_stopwords]

    return " ".join(processed)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
df['cleaned_text']=df['cleaned_text'].apply(preprocess_arabic_text)

/tmp/ipython-input-3856154412.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_text']=df['cleaned_text'].apply(preprocess_arabic_text)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
def my_query(query, top_similar=2):
    query_preprocessed = normalize_arabic(query)
    query_preprocessed = handle_emojis(query_preprocessed)
    query_preprocessed = handle_numbers_and_special_chars(query_preprocessed)
    query_preprocessed = remove_arabic_punctuations(query_preprocessed)
    query_preprocessed = remove_diacritics(query_preprocessed)
    query_preprocessed = preprocess_arabic_text(query_preprocessed)

    query_vec = vectorizer.transform([query_preprocessed])

    similarities = cosine_similarity(query_vec, vec_data).flatten()

    top_k_indices = similarities.argsort()[::-1][:top_similar]

    return top_k_indices, similarities[top_k_indices]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Vectorization using TF-IDF
vectorizer = TfidfVectorizer()
vec_data = vectorizer.fit_transform(df['cleaned_text'])

def search_documents(query, top_similar=10):
    # Preprocess the query
    query_preprocessed = normalize_arabic(query)
    query_preprocessed = handle_emojis(query_preprocessed)
    query_preprocessed = handle_numbers_and_special_chars(query_preprocessed)
    query_preprocessed = remove_arabic_punctuations(query_preprocessed)
    query_preprocessed = remove_diacritics(query_preprocessed)
    query_preprocessed = preprocess_arabic_text(query_preprocessed)

    # Vectorize the query
    query_vec = vectorizer.transform([query_preprocessed])

    # Calculate Cosine similarity
    similarities = cosine_similarity(query_vec, vec_data).flatten()

    # Sort the result and Retrieve the most 10 documents similar to the Query
    top_k_indices = similarities.argsort()[::-1][:top_similar]

    return df.iloc[top_k_indices]

In [ ]:
!pip -q install nltk

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
title_tokens = df['Title'].apply(word_tokenize)
content_tokens = df['Content'].apply(word_tokenize)

In [ ]:
display(title_tokens.head())

0    [تيرتل, تري, لابز, للتقنيات, الحيويه, تحصل, عل...
1    [تعد, دراسه, الجدوي, لمشروعك, الناشء, 6, عوامل...
2    [منح, جاءزه, نوبل, الطب, لاكتشاف, مجال, التهاب...
3    [هيءه, الغذاء, والدواء, الامريكيه, لقاح, مودرن...
4    [حظر, بروتين, الجهاز, المناعي, يساعد, علي, محا...
Name: Title, dtype: object

In [ ]:
print("TF-IDF")

query = " الذكاء الاصطناعي"
processed_query = preprocess_arabic_text(query)
query_vec = vectorizer.transform([processed_query])


cosine_sim = cosine_similarity(query_vec, vec_data).flatten()

top_indices = cosine_sim.argsort()[::-1][:9]


print("\nQuery:", query)
print("\n  most similar documents:\n")
for idx in top_indices:
    print(f"[{df['Title'].iloc[idx]}] ({df['Category'].iloc[idx]})")
    print(f"Link: {df['Link'].iloc[idx]}")
    print(f"Score: {cosine_sim[idx]:.4f}\n")

TF-IDF

Query:  الذكاء الاصطناعي

  most similar documents:

[المملكه تعتزم استثمار يزيد 5 مليارات دولار الذكاء] (ريادة أعمال)
Link: https://ryadiybusiness.com/%d8%a7%d9%84%d9%85%d9%85%d9%84%d9%83%d8%a9-%d8%aa%d8%b9%d8%aa%d8%b2%d9%85-%d8%a7%d8%b3%d8%aa%d8%ab%d9%85%d8%a7%d8%b1-%d9%85%d8%a7-%d9%8a%d8%b2%d9%8a%d8%af-%d8%b9%d9%86-5-%d9%85%d9%84%d9%8a%d8%a7%d8%b1/
Score: 0.7900

[الذكاء الاصطناعي ساحات المعارك سيناريوهات مرعبه] (علوم وتكنولوجيا)
Link: https://asharq.com/ar/3NHONPgLNP6tUYjmuMwQsi-الذكاء-الاصطناعي-في-ساحات-المعارك/
Score: 0.7870

[نسدي استراتيجيه سعوديه جديده للبيانات والذكاء الاصطناعي] (علوم وتكنولوجيا)
Link: https://asharq.com/ar/1BnvyHiWoNcsL6E2jWs89H-نسدي-استراتيجية-سعودية-جديدة-للبيانات/
Score: 0.7640

[السعوديه بناء منصه سحابيه للذكاء الاصطناعي والتعلم] (علوم وتكنولوجيا)
Link: https://asharq.com/ar/4ceP8EonBD8cTrQXJe3VTZ-السعودية-أول-منصة-سحابية-للذكاء/
Score: 0.7515

[تقرير الذكاء الاصطناعي يسرع الاختراقات مجالات الطاقه والمياه والنفايات والمدن] (ريادة أعمال)
Link: https://ryadiybusiness.com/%d8%aa%d9%82%d8%b1%d9%8a%d8%b1-%d8%a7%d9%84%d8%b0%d9%83%d8%a7%d8%a1-%d8%a7%d9%84%d8%a7%d8%b5%d8%b7%d9%86%d8%a7%d8%b9%d9%8a-%d9%8a%d8%b3%d8%b1%d9%91%d8%b9-%d8%a7%d9%84%d8%a7%d8%ae%d8%aa%d8%b1%d8%a7/
Score: 0.7287

[وزراء التعليم العرب يدعون لانشاء مختبرات لالذكاء الاصطناعي] (ريادة أعمال)
Link: https://ryadiybusiness.com/%d9%88%d8%b2%d8%b1%d8%a7%d8%a1-%d8%a7%d9%84%d8%aa%d8%b9%d9%84%d9%8a%d9%85-%d8%a7%d9%84%d8%b9%d8%b1%d8%a8-%d9%8a%d8%af%d8%b9%d9%88%d9%86-%d9%84%d8%a5%d9%86%d8%b4%d8%a7%d8%a1-%d9%85%d8%ae%d8%aa%d8%a8/
Score: 0.7144

[16 المءسسات السعوديه تعتبر الذكاء الاصطناعي اولويه قصوي] (ريادة أعمال)
Link: https://ryadiybusiness.com/16-%d9%85%d9%86-%d8%a7%d9%84%d9%85%d8%a4%d8%b3%d8%b3%d8%a7%d8%aa-%d8%a7%d9%84%d8%b3%d8%b9%d9%88%d8%af%d9%8a%d8%a9-%d8%aa%d8%b9%d8%aa%d8%a8%d8%b1-%d8%a7%d9%84%d8%b0%d9%83%d8%a7%d8%a1-%d8%a7%d9%84/
Score: 0.7027

[16 المءسسات السعوديه تعتبر الذكاء الاصطناعي اولويه قصوي] (ريادة أعمال)
Link: https://ryadiybusiness.com/16-%d9%85%d9%86-%d8%a7%d9%84%d9%85%d8%a4%d8%b3%d8%b3%d8%a7%d8%aa-%d8%a7%d9%84%d8%b3%d8%b9%d9%88%d8%af%d9%8a%d8%a9-%d8%aa%d8%b9%d8%aa%d8%a8%d8%b1-%d8%a7%d9%84%d8%b0%d9%83%d8%a7%d8%a1-%d8%a7%d9%84/
Score: 0.7027

[القاهره رواد2030 يطلق جلسه نقاشيه بعنوان فرص رياده الاعمال بعصر الذكاء] (ريادة أعمال)
Link: https://ryadiybusiness.com/%d8%a7%d9%84%d9%82%d8%a7%d9%87%d8%b1%d8%a9-%d8%b1%d9%88%d8%a7%d8%af2030-%d9%8a%d8%b7%d9%84%d9%82-%d8%ac%d9%84%d8%b3%d8%a9-%d9%86%d9%82%d8%a7%d8%b4%d9%8a%d8%a9-%d8%a8%d8%b9%d9%86%d9%88%d8%a7%d9%86/
Score: 0.6837

In [ ]:
import gradio as gr

interface = gr.Interface(
    fn=search_documents,
    inputs=gr.Textbox(label="Enter your search query"),
    outputs=gr.Textbox(label="Top Matching Paragraphs"),
    title="📚 Search about any thing you want",
)

In [ ]:
interface.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://ff4b25d66d70879d82.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)